- name: install git
  hosts: all
  become: yes
  tasks:
    - name: install git
      ansible.builtin.package:
        name: git
        state: present

    - name: Check git version
      ansible.builtin.shell: git --version > /tmp/git_output.txt
      register: git_output

    - name: print output
      ansible.builtin.debug:
        msg: "{{ git_output.stdout }}"